# Generated by Django 4.0.5 on 2022-06-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
