# Generated by Django 4.0.5 on 2022-06-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0007_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='design',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='usability',
            field=models.IntegerField(default=0),
        ),
    ]
