# Generated by Django 4.0.5 on 2022-06-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0010_project_design_project_usability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='project_id',
            new_name='pro_id',
        ),
    ]
